= 有关asciidoc的语法

== 标题

标题有两种标记方式，两行式和一行式，都支持最多四级标题，分别是

第一种：
..............................
书名
=====
一级标题
----------
二级标题
~~~~~~~~~~~~~~
三级标题
^^^^^^^^^^^^^^
四级标题
++++++++++++++
..............................

和第二种：
............................
= 书名 =
== 一级标题 ==
=== 二级标题 ===
==== 三级标题 ====
===== 四级标题 ======
............................

注意第二种单行的风格右边的那部分标记也可以省略的，也就是可以这样：
...............................
= 书名
== 一级标题
=== 二级标题
==== 三级标题
===== 四级标题
...............................


== 段落

段落没有单独的标记，直接空一行就OK，但是记得新的段落需要顶格写


== 字体样式

*粗体* ：

    *粗体* <1>

<1> 如果加粗字体两旁有其他中文字体的话，需要用空格隔开，英文字体则无此问题。

'斜体' ：

    '斜体'

[underline]#下划线# ：

    [underline]#下划线#

[big]#大号# ：

    [big]#大号#

[red]#有色字体# ：

    [red]#有色字体#

== 列表

列表对应html里面的<li>标签，分为四种：

- 无序列表
- 有序列表
- 标签列表
- callout列表

=== 无序列表

<ul>标签，无序列表一般开头是一个小圆点，使用的语法为：
......................
- 无序列表
- 有序列表
- 标签列表
- callout列表
......................

支持多级嵌套，语法格式为：
......................
- 第一级 <1>
* 第二级 <2>
** 第三级
*** 第四级
**** 第五级
***** 第六级 <3>
......................

<1> 最高一级用“-”表示。
<2> 接下来用一个或多个“*”表示。
<3> 最多支持5个“*”，也就是6级嵌套。 

- 第一级
* 第二级
** 第三级
*** 第四级
**** 第五级
***** 第六级

=== 有序列表

<ol>标签，每一个列表项都有序号，并且按照序号增减排列

.............................

2. 阿拉伯数字作为序号（显式）<1>
a. 小写字母作为序号（显式）
a. 小写字母作为序号（显式）<3>
2. 阿拉伯数字作为序号（显式）
F. 大写字母作为序号（显式）<3>
ii) 小写罗马字母作为序号（显式）
IX) 大写罗马字母作为序号（显式）


. 阿拉伯数字作为序号（隐式）<2>
.. 小写字母作为序号（隐式）
.. 小写字母作为序号（隐式）
... 小写罗马字母作为序号（隐式）
.... 大写字母作为序号（隐式）
..... 大写罗马字母作为序号（隐式）
.. 小写字母作为序号（隐式）
..... 大写罗马字母作为序号（隐式）

.............................

<1> 显式语法在每个条目的开头指定序号的类型和起始大小。
<2> 隐式语法不指定序号的类型和大小，而将这些交给AsciiDoc来决定。
<3> 每当序号类型改变时，条目就会自动缩进到更低的一级。

出来的效果是

2. 阿拉伯数字作为序号（显式）
a. 小写字母作为序号（显式）
a. 小写字母作为序号（显式）
2. 阿拉伯数字作为序号（显式）
F. 大写字母作为序号（显式）
ii) 小写罗马字母作为序号（显式）
IX) 大写罗马字母作为序号（显式）


. 阿拉伯数字作为序号（隐式）
.. 小写字母作为序号（隐式）
.. 小写字母作为序号（隐式）
... 小写罗马字母作为序号（隐式）
.... 大写字母作为序号（隐式）
..... 大写罗马字母作为序号（隐式）
.. 小写字母作为序号（隐式）
..... 大写罗马字母作为序号（隐式）

切换一次前缀，便缩进一次，
但是如果切换的是“更高优先级”的则和前面的进行对应，但是接下来的缩进就是以这次为开始了，即使接下来的是“越级”了的

=== 标签列表

类似<dt>标签，标签列表的每一个条目都以用户指定的标签开头
..........................
定义1:: <1>
  “定义1”是……
  定义1.1:::
    “定义1.1”是……
    定义1.1.1::::
      “定义1.1.1”是……
定义2::
  “定义2”是……
  定义2.2;; <1>
    “定义2.2”是……
...........................

<1> 可以使用两个，三个，四个“:”或两个“;”进行标签列表条目的标记。

=== Callout列表

Callout在分析代码的时候非常有用！几乎可以在任何用DocBook写的技术书籍里面看到它的身影。我们来看个例子：

  .........................
  - 第一级 \<1>
  * 第二级 \<2>
  ** 第三级
  *** 第四级
  **** 第五级
  ***** 第六级 \<3>
  .........................
  <1> 最高一级用“-”表示。
  <2> 接下来用一个或多个“*”表示。
  <3> 最多支持5个“*”，也就是6级嵌套。

这便是之前的无序列表的例子



后面的内容实在是太多了，我直接把原文给拷贝过来了:)





https://www.baidu.com



















